import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json"};
const UA="Mozilla/5.0 (compatible; JobHuntOS/2.0; +https://hashmi.website)";
function clean(s:string){return s.replace(/<[^>]*>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\\s+/g," ").trim()}
function absolute(u:string){try{return new URL(u).toString().replace(/\\/$/,"")}catch{return null}}
function extractGoogle(html:string,limit:number){const out:any[]=[];const seen=new Set<string>();const re=/<a[^>]+href="([^"]+)"[^>]*>([\\s\\S]*?)<\\/a>/gi;let m;while((m=re.exec(html))&&out.length<limit*3){let u=m[1];if(u.startsWith('/url?')){try{u=new URL('https://www.google.com'+u).searchParams.get('q')||''}catch{}}const url=absolute(u);const title=clean(m[2]);if(url&&!/google\\./i.test(new URL(url).hostname)&&title.length>2&&!seen.has(url)){seen.add(url);out.push({url,title,source_name:'Google public web search',source_type:'search'})}}return out.slice(0,limit)}
function extractBing(html:string,limit:number){const out:any[]=[];const seen=new Set<string>();const re=/<li class="b_algo"[\\s\\S]*?<a href="([^"]+)"[^>]*>([\\s\\S]*?)<\\/a>/gi;let m;while((m=re.exec(html))&&out.length<limit){const url=absolute(m[1]);const title=clean(m[2]);if(url&&title&&!seen.has(url)){seen.add(url);out.push({url,title,source_name:'Bing public web search',source_type:'search'})}}return out}
async function fetchSearch(engine:string,q:string,limit:number){try{const url=engine==='bing'?`https://www.bing.com/search?q=${encodeURIComponent(q)}&count=${limit}`:`https://www.google.com/search?q=${encodeURIComponent(q)}&num=${limit}`;const r=await fetch(url,{headers:{"User-Agent":UA,"Accept-Language":"en-US,en;q=0.9"}});if(!r.ok)return [];const html=await r.text();return engine==='bing'?extractBing(html,limit):extractGoogle(html,limit)}catch{return []}}
function roleQueries(q:string,loc:string){return [...new Set([`${q} jobs ${loc}`,`${q} careers ${loc}`,`${q} site:boards.greenhouse.io ${loc}`,`${q} site:jobs.lever.co ${loc}`,`${q} site:ashbyhq.com ${loc}`])].slice(0,5)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});try{if(!req.headers.get('Authorization'))throw Error('Authorization required');const b=await req.json().catch(()=>({}));const q=String(b.query||'finance analyst').trim();const loc=String(b.location||'Mumbai, India').trim();const limit=Math.min(Math.max(Number(b.limit||10),1),20);const all:any[]=[];const seen=new Set<string>();for(const query of roleQueries(q,loc)){for(const engine of ['google','bing']){const rs=await fetchSearch(engine,query,Math.min(8,limit));for(const x of rs){if(!seen.has(x.url)){seen.add(x.url);all.push({...x,query});}if(all.length>=limit)break}if(all.length>=limit)break}if(all.length>=limit)break}return new Response(JSON.stringify({ok:true,query:q,location:loc,count:all.length,results:all.slice(0,limit),provider:'public web search (Google/Bing)',fetched_at:new Date().toISOString()}),{headers:H})}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:400,headers:H})}})
